# Generated by Django 3.0.4 on 2020-03-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lengths',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxSkillLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=15, unique=True)),
                ('is_elite', models.BooleanField()),
                ('max_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.MaxSkillLevels')),
            ],
        ),
        migrations.CreateModel(
            name='SkillRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.Skills')),
            ],
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('members', models.BooleanField(default=False)),
                ('questPoints', models.IntegerField(default=1)),
                ('release_date', models.DateField()),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.Ages')),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.Difficulties')),
                ('length', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='API.Lengths')),
                ('required_quests', models.ManyToManyField(to='API.Quests')),
                ('required_skills', models.ManyToManyField(to='API.SkillRequirements')),
            ],
        ),
    ]
